<a href="https://colab.research.google.com/github/r-ap/TrainingMachineLearning/blob/main/BFI_PYIM_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [ ]:
import numpy as np

## Array & NDarray

**np.array()**

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

**np.zeros()**

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

**np.ones()**

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

**np.empty()**

In [ ]:
np.empty(5)

array([1.93182197e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

**np.arange()**

In [ ]:
np.arange(1,4) #start, stop, step

array([1, 2, 3])

**np.linspace()**

In [ ]:
np.linspace(2,8,100) #start, stop, jumlah elemen

array([2.        , 2.06060606, 2.12121212, 2.18181818, 2.24242424,
       2.3030303 , 2.36363636, 2.42424242, 2.48484848, 2.54545455,
       2.60606061, 2.66666667, 2.72727273, 2.78787879, 2.84848485,
       2.90909091, 2.96969697, 3.03030303, 3.09090909, 3.15151515,
       3.21212121, 3.27272727, 3.33333333, 3.39393939, 3.45454545,
       3.51515152, 3.57575758, 3.63636364, 3.6969697 , 3.75757576,
       3.81818182, 3.87878788, 3.93939394, 4.        , 4.06060606,
       4.12121212, 4.18181818, 4.24242424, 4.3030303 , 4.36363636,
       4.42424242, 4.48484848, 4.54545455, 4.60606061, 4.66666667,
       4.72727273, 4.78787879, 4.84848485, 4.90909091, 4.96969697,
       5.03030303, 5.09090909, 5.15151515, 5.21212121, 5.27272727,
       5.33333333, 5.39393939, 5.45454545, 5.51515152, 5.57575758,
       5.63636364, 5.6969697 , 5.75757576, 5.81818182, 5.87878788,
       5.93939394, 6.        , 6.06060606, 6.12121212, 6.18181818,
       6.24242424, 6.3030303 , 6.36363636, 6.42424242, 6.48484

### Add, Remove, Sort

In [ ]:
#Add

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.append(arr,5)

array([1, 2, 3, 4, 5, 6, 7, 8, 5])

In [ ]:
#Remove

np.delete(arr,0)

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Sort - ascending

arr2 = np.array([6,8,2,4,6,0,3])
np.sort(arr2)

array([0, 2, 3, 4, 6, 6, 8])

In [ ]:
#Sort - descending

-np.sort(-arr2)

array([8, 6, 6, 4, 3, 2, 0])

### Shape and Size

**ndarray.ndim**

In [ ]:
arr2.ndim

1

**ndarray.size**

In [ ]:
arr2.size

7

**ndarray.shape**

In [ ]:
arr2.shape

(7,)

### Reshape

In [ ]:
array = np.array([[1,3],[3,4],[4,5]])
print(array)
print(array.shape)

[[1 3]
 [3 4]
 [4 5]]
(3, 2)


In [ ]:
array_reshape = array.reshape(2,3)
print(array_reshape)
print(array_reshape.shape)

[[1 3 3]
 [4 4 5]]
(2, 3)


### Transpose

In [ ]:
array.T

array([[1, 3, 4],
       [3, 4, 5]])

## Ubah Array 1D ke 2D

**np.newaxis**

In [ ]:
arr2

array([6, 8, 2, 4, 6, 0, 3])

In [ ]:
arr2[np.newaxis]

array([[6, 8, 2, 4, 6, 0, 3]])

In [ ]:
arr2[np.newaxis,:]

array([[6, 8, 2, 4, 6, 0, 3]])

In [ ]:
arr2[np.newaxis,:].shape

(1, 7)

**np.expand_dims**

In [ ]:
arr3 = np.expand_dims(arr2, axis=1)
arr3.shape

(7, 1)

In [ ]:
arr3

array([[6],
       [8],
       [2],
       [4],
       [6],
       [0],
       [3]])

In [ ]:
arr4 = np.expand_dims(arr2, axis=0)
arr4.shape

(1, 7)

In [ ]:
arr4

array([[6, 8, 2, 4, 6, 0, 3]])

## Indexing dan Slicing

In [ ]:
print(arr2)
print(array)

[8 6 6 4 3 2 0]
[[1 3]
 [3 4]
 [4 5]]


## Operasi Dasar NumPy

In [ ]:
ARR1 = np.array([1,2,3,4,5])
ARR2 = np.array([2,3,4,5,6])
print(ARR1)
print(ARR2)

[1 2 3 4 5]
[2 3 4 5 6]


### Aritmatika

### Agregat

## Flatten N-Dimensional Array

In [ ]:
arr_exp = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
arr_exp.flatten()